#!/bin/bash
sudo maskman
echo "Welcome"
sleep 1
echo "Closing CUPS"
xterm -e "sudo systemctl stop cups && sudo systemctl disable cups && exit"
echo "Stopped and Disabled CUPS"
echo "Running snort monitor"
#xterm -e "sudo apt update"
#gnome-terminal -e "watch -n 0.2 nvidia-smi"
#gnome-terminal -e "watch -n 0.2 netstat -lvptu"
#gnome-terminal -e "watch -n 0.2 netstat -lvpa"
#gnome-terminal -e "watch -n 0.1 python3 /home/maskman/Desktop/login/rangeip.py"
#gnome-terminal -e "sudo iftop -i eno1"
#gnome-terminal -e "sudo tcpdump -i eno1 port 22"
gnome-terminal -e "sudo bash /home/maskman/Documents/scripts/login/snortstartup.sh"
#echo "Done !!!"
sleep 1
echo "Done Sir !!"
echo "Now Exiting !!" && exit
